var array = ["Banana", "Apples", "Oranges", "Blueberries"];
array.shift();
console.log(array);
array.sort();
console.log(array);
array.push("Kiwi");
console.log(array);
delete array[0];
console.log(array);
array.reverse();
console.log(array);
array.pop();
console.log(array);