# Generated by Django 3.1.2 on 2020-10-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rental',
            name='rental_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
