# Generated by Django 3.1.2 on 2020-10-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_auto_20201001_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='return_date',
            field=models.DateField(null=True),
        ),
    ]
